###################################################################

# Created by write_sdc on Mon Dec 29 21:47:30 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 0.1 [get_ports awready]
set_load -pin_load 0.1 [get_ports wready]
set_load -pin_load 0.1 [get_ports {bresp[1]}]
set_load -pin_load 0.1 [get_ports {bresp[0]}]
set_load -pin_load 0.1 [get_ports bvalid]
set_load -pin_load 0.1 [get_ports arready]
set_load -pin_load 0.1 [get_ports {rdata[31]}]
set_load -pin_load 0.1 [get_ports {rdata[30]}]
set_load -pin_load 0.1 [get_ports {rdata[29]}]
set_load -pin_load 0.1 [get_ports {rdata[28]}]
set_load -pin_load 0.1 [get_ports {rdata[27]}]
set_load -pin_load 0.1 [get_ports {rdata[26]}]
set_load -pin_load 0.1 [get_ports {rdata[25]}]
set_load -pin_load 0.1 [get_ports {rdata[24]}]
set_load -pin_load 0.1 [get_ports {rdata[23]}]
set_load -pin_load 0.1 [get_ports {rdata[22]}]
set_load -pin_load 0.1 [get_ports {rdata[21]}]
set_load -pin_load 0.1 [get_ports {rdata[20]}]
set_load -pin_load 0.1 [get_ports {rdata[19]}]
set_load -pin_load 0.1 [get_ports {rdata[18]}]
set_load -pin_load 0.1 [get_ports {rdata[17]}]
set_load -pin_load 0.1 [get_ports {rdata[16]}]
set_load -pin_load 0.1 [get_ports {rdata[15]}]
set_load -pin_load 0.1 [get_ports {rdata[14]}]
set_load -pin_load 0.1 [get_ports {rdata[13]}]
set_load -pin_load 0.1 [get_ports {rdata[12]}]
set_load -pin_load 0.1 [get_ports {rdata[11]}]
set_load -pin_load 0.1 [get_ports {rdata[10]}]
set_load -pin_load 0.1 [get_ports {rdata[9]}]
set_load -pin_load 0.1 [get_ports {rdata[8]}]
set_load -pin_load 0.1 [get_ports {rdata[7]}]
set_load -pin_load 0.1 [get_ports {rdata[6]}]
set_load -pin_load 0.1 [get_ports {rdata[5]}]
set_load -pin_load 0.1 [get_ports {rdata[4]}]
set_load -pin_load 0.1 [get_ports {rdata[3]}]
set_load -pin_load 0.1 [get_ports {rdata[2]}]
set_load -pin_load 0.1 [get_ports {rdata[1]}]
set_load -pin_load 0.1 [get_ports {rdata[0]}]
set_load -pin_load 0.1 [get_ports {rresp[1]}]
set_load -pin_load 0.1 [get_ports {rresp[0]}]
set_load -pin_load 0.1 [get_ports rvalid]
